// c82 — Refund unearned money when a matter ends.
//
// At matter close (or when the client ends the relationship) the system
// works out what in trust is unearned, prepares a final invoice and a refund
// for the lawyer to approve, and blocks closing until the client's trust
// balance for the matter is zero or a lawyer records why money is held
// (e.g. a disputed amount stays in trust).
//
// planCloseout() is a PURE calculation and can run today as a preview.
// executeRefund() is a PLACEHOLDER gated on attorney + CPA sign-off
// (c75 rule list, c76 ledger, c82 refund rules).

import { assertNonNegativeCents, type Cents } from "./money";
import { requireGates, type GateRegistry, COMPLIANCE_GATES } from "./approvals";
import { InvalidTransitionError, type Actor } from "./timeEntries";

export interface CloseoutInput {
  clientId: string;
  matterId: string;
  trustBalanceCents: Cents;
  /** Amount in trust that is disputed and must stay until resolved. */
  disputedHeldCents: Cents;
  /**
   * Earned and billable but not yet paid: approved unbilled time and costs,
   * plus completed fixed-fee milestones not yet transferred (c52).
   */
  earnedUnpaidCents: Cents;
  /** Open amounts on already-sent invoices for this matter. */
  openInvoicesCents: Cents;
}

export interface CloseoutPlan {
  /** Final invoice amount for newly billed earned work. */
  finalInvoiceCents: Cents;
  /** Proposed draw from trust for the final invoice and open invoices (floor no longer applies at close). */
  proposedTrustDrawCents: Cents;
  /** What the client still owes after the trust draw. */
  clientStillOwesCents: Cents;
  /** Proposed refund of unearned funds to the client. */
  proposedRefundCents: Cents;
  /** Stays in trust with a lawyer-recorded reason. */
  heldCents: Cents;
  /** True if everything nets to zero with no hold needed. */
  canCloseWithoutHold: boolean;
}

export function planCloseout(i: CloseoutInput): CloseoutPlan {
  assertNonNegativeCents(i.trustBalanceCents, "trustBalanceCents");
  assertNonNegativeCents(i.disputedHeldCents, "disputedHeldCents");
  assertNonNegativeCents(i.earnedUnpaidCents, "earnedUnpaidCents");
  assertNonNegativeCents(i.openInvoicesCents, "openInvoicesCents");
  if (i.disputedHeldCents > i.trustBalanceCents) throw new Error("Disputed amount held cannot exceed the trust balance");

  const available = i.trustBalanceCents - i.disputedHeldCents;
  const owed = i.earnedUnpaidCents + i.openInvoicesCents;
  // PLACEHOLDER assumption pending c75: at close the c50 floor no longer applies,
  // and the lawyer may apply trust to earned, invoiced fees. Confirm with attorney + CPA.
  const draw = Math.min(available, owed);
  const refund = available - draw;
  return {
    finalInvoiceCents: i.earnedUnpaidCents,
    proposedTrustDrawCents: draw,
    clientStillOwesCents: owed - draw,
    proposedRefundCents: refund,
    heldCents: i.disputedHeldCents,
    canCloseWithoutHold: i.disputedHeldCents === 0,
  };
}

export interface HoldRecord {
  amountCents: Cents;
  reason: string;
  recordedByUserId: string;
  recordedAt: string;
}

/**
 * Closing gate: the matter can close only if the client's trust balance for
 * it is zero, or every remaining cent is covered by a lawyer-recorded hold.
 */
export function canCloseMatter(trustBalanceCents: Cents, holds: HoldRecord[]): { ok: boolean; reason?: string } {
  const held = holds.reduce((a, h) => a + h.amountCents, 0);
  if (trustBalanceCents === 0) return { ok: true };
  if (holds.some((h) => !h.reason.trim())) return { ok: false, reason: "Every hold needs a reason." };
  if (held === trustBalanceCents) return { ok: true };
  return {
    ok: false,
    reason: `Trust balance ${trustBalanceCents} is not zero and holds cover ${held}. Finish the refund or record a hold for the rest.`,
  };
}

export function recordHold(amountCents: Cents, reason: string, actor: Actor, now: Date): HoldRecord {
  if (actor.role !== "attorney") throw new InvalidTransitionError("open", "held", "only a lawyer can record why money stays in trust");
  assertNonNegativeCents(amountCents, "hold");
  if (!reason.trim()) throw new Error("A hold needs a reason");
  return { amountCents, reason, recordedByUserId: actor.userId, recordedAt: now.toISOString() };
}

export type RefundStatus = "proposed" | "lawyer_approved" | "issued" | "cancelled";

export interface RefundProposal {
  matterId: string;
  clientId: string;
  amountCents: Cents;
  status: RefundStatus;
  approvedByUserId: string | null;
  /** Refund letter generated by the Document engine (c85) from an approved template. */
  letterDocumentId: string | null;
}

export function approveRefund(r: RefundProposal, actor: Actor): RefundProposal {
  if (actor.role !== "attorney") throw new InvalidTransitionError(r.status, "lawyer_approved", "only a lawyer approves a refund");
  if (r.status !== "proposed") throw new InvalidTransitionError(r.status, "lawyer_approved");
  return { ...r, status: "lawyer_approved", approvedByUserId: actor.userId };
}

/**
 * PLACEHOLDER — issuing the refund out of trust. Throws until the trust
 * review (c75), ledger (c76) and refund rules (c82) are signed off by a
 * Texas attorney and a CPA. The refund letter template is also a
 * placeholder until attorney-approved (copy.ts "refund_letter").
 */
export async function executeRefund(r: RefundProposal, registry: GateRegistry = COMPLIANCE_GATES): Promise<never> {
  if (r.status !== "lawyer_approved") throw new InvalidTransitionError(r.status, "issued", "the lawyer must approve the refund first");
  requireGates(["trust_rules_c75", "trust_ledger_c76", "refund_rules_c82"], "refund unearned funds from trust", registry);
  throw new Error("executeRefund: approved but not yet implemented; build with the c76 trust ledger.");
}
